Repository nimblehq/js-framework-benchmark, pull requests merged in 2023-06, with the labels that each got.

#104 [#40][#41] [Backend][Frontend] As a user I can logout
  nextjs-13/public/images/icons/three-dots-vertical.svg
  nextjs-13/src/app/auth/sign-in/page.test.tsx
  nextjs-13/src/app/auth/sign-in/page.tsx
  nextjs-13/src/components/Dropdown/index.test.tsx
  nextjs-13/src/components/Dropdown/index.tsx
  nextjs-13/src/components/Header/UserProfile.tsx
  nextjs-13/src/stylesheets/components/_dropdown.scss
  nextjs-13/src/stylesheets/components/_index.scss
  nextjs-13/yarn.lock
Labels: type : feature

#109 [#60] [Frontend] As a user I can logout
  remix/.env.sample
  remix/app/components/Dropdown/index.test.tsx
  remix/app/components/Dropdown/index.tsx
  remix/app/components/Header/UserProfile.tsx
  remix/app/components/Header/index.tsx
  remix/app/routes/auth.sign-out.test.tsx
  remix/app/routes/auth.sign-out.tsx
  remix/app/tests/factories/session.factory.ts
  remix/jest.config.js
  remix/package-lock.json
  remix/package.json
  remix/remix.config.js
Labels: type : feature, remix

#105 [#59] [Backend] As a user I can logout
  remix/app/routes/auth.sign-out.test.tsx
  remix/app/tests/helpers/request.ts
Labels: type : feature, remix

#112 [#63] [Backend] As a user I can create a newsletter
  remix/app/lib/handler/app.handler.test.ts
  remix/app/lib/handler/app.handler.ts
  remix/app/repositories/newsletter.server.test.ts
  remix/app/repositories/newsletter.server.ts
  remix/app/root.tsx
  remix/app/routes/_app.newsletter.create.test.tsx
  remix/app/routes/_app.newsletter.create.tsx
  remix/app/services/auth.server.ts
  remix/app/tests/factories/newsletter.factory.ts
  remix/app/tests/factories/user.factory.ts
  remix/app/tests/helpers/request.ts
  remix/package-lock.json
  remix/package.json
  remix/prisma/migrations/20230601094138_init/migration.sql
  remix/prisma/migrations/20230606073858_init/migration.sql
  remix/prisma/schema.prisma
Labels: type : feature, remix

#106 [#45] [Frontend] As a user I can create a newsletter
  nextjs-13/package-lock.json
  nextjs-13/package.json
  nextjs-13/src/app/layout.tsx
  nextjs-13/src/app/page.test.tsx
  nextjs-13/src/app/page.tsx
  nextjs-13/src/app/toast-container-wrapper.tsx
  nextjs-13/src/components/AppLayout/index.tsx
  nextjs-13/src/components/CreateNewsletterModal/index.test.tsx
  nextjs-13/src/components/CreateNewsletterModal/index.tsx
  nextjs-13/src/lib/request/manager.ts
  nextjs-13/src/lib/toast/makeToast.ts
  nextjs-13/src/stylesheets/application.scss
  nextjs-13/src/stylesheets/components/_create-newsletter-modal.scss
  nextjs-13/src/stylesheets/components/_index.scss
  nextjs-13/src/stylesheets/screens/_home.scss
  nextjs-13/src/stylesheets/screens/_index.scss
  nextjs-13/yarn.lock
Labels: type : feature

#107 [#42] [Backend] As a user I can list newsletters
  nextjs-13/prisma/schema.prisma
  nextjs-13/src/app/api/v1/newsletter/route.test.ts
  nextjs-13/src/app/api/v1/newsletter/route.ts
  nextjs-13/src/repositories/newsletter.repository.test.ts
  nextjs-13/src/repositories/newsletter.repository.ts
Labels: type : feature

#120 [#64] [Frontend] As a user I can create a newsletter
  remix/app/components/AppLink/index.test.tsx
  remix/app/components/AppLink/index.tsx
  remix/app/components/Dropdown/index.tsx
  remix/app/components/FormInput/Error/index.test.tsx
  remix/app/components/FormInput/Error/index.tsx
  remix/app/components/FormInput/Label/index.test.tsx
  remix/app/components/FormInput/Label/index.tsx
  remix/app/components/FormInput/index.test.tsx
  remix/app/components/FormInput/index.tsx
  remix/app/components/SubmitButton/index.test.tsx
  remix/app/components/SubmitButton/index.tsx
  remix/app/components/SubmitButton/loading.test.tsx
  remix/app/components/SubmitButton/loading.tsx
  remix/app/helpers/.keep
  remix/app/helpers/localStorage.helper.ts
  remix/app/lib/handler/app.handler.test.ts
  remix/app/lib/handler/app.handler.ts
  remix/app/lib/notification/showNotification.ts
  remix/app/root.tsx
  remix/app/routes/_app._index.tsx
  remix/app/routes/_app.newsletter.create.test.tsx
  remix/app/routes/_app.newsletter.create.tsx
  remix/app/routes/auth.sign-in.tsx
  remix/app/routes/auth.sign-out.test.tsx
  remix/app/tests/helpers/request.ts
  remix/app/types/Notification.ts
  remix/app/types/index.ts
  remix/package-lock.json
  remix/package.json
Labels: type : feature, remix

#122 [#61] [Backend] As a user I can list newsletters
  remix/app/repositories/newsletter.server.test.ts
  remix/app/repositories/newsletter.server.ts
  remix/app/routes/_app._index.test.tsx
  remix/app/routes/_app._index.tsx
Labels: type : feature, remix

#124 [#62] [Frontend] As a user I can list newsletters
  remix/app/components/Header/index.tsx
  remix/app/components/NewsletterList/index.test.tsx
  remix/app/components/NewsletterList/index.tsx
  remix/app/routes/_app._index.tsx
Labels: type : feature, remix

#110 [#43] [Frontend] As a user I can list newsletters
  nextjs-13/src/app/api/v1/me/route.test.ts
  nextjs-13/src/app/api/v1/newsletter/route.test.ts
  nextjs-13/src/app/auth/sign-in/page.tsx
  nextjs-13/src/app/page.test.tsx
  nextjs-13/src/app/page.tsx
  nextjs-13/src/components/AppLayout/index.tsx
  nextjs-13/src/components/CreateNewsletterModal/index.tsx
  nextjs-13/src/components/ListNewsletter/index.test.tsx
  nextjs-13/src/components/ListNewsletter/index.tsx
  nextjs-13/src/lib/handler/app.handler.test.ts
  nextjs-13/src/stylesheets/components/_index.scss
  nextjs-13/src/stylesheets/components/_list-newsletter.scss
  nextjs-13/src/stylesheets/layouts/_app.scss
  nextjs-13/src/stylesheets/layouts/_auth.scss
  nextjs-13/src/stylesheets/screens/_home.scss
Labels: type : feature

#126 [#65] [Backend] As a user I can edit a newsletter
  remix/app/repositories/newsletter.server.test.ts
  remix/app/repositories/newsletter.server.ts
  remix/app/root.tsx
  remix/app/routes/_app.newsletter.update.$id.test.tsx
  remix/app/routes/_app.newsletter.update.$id.tsx
Labels: type : feature, remix

#113 [#48] [Backend] As a user I can delete a newsletter
  nextjs-13/src/app/api/v1/newsletter/[id]/route.test.ts
  nextjs-13/src/app/api/v1/newsletter/[id]/route.ts
  nextjs-13/src/repositories/newsletter.repository.test.ts
  nextjs-13/src/repositories/newsletter.repository.ts
Labels: type : feature

#130 [#66] [Frontend] As a user I can edit a newsletter
  remix/app/components/AppLink/helper.ts
  remix/app/components/AppLink/index.tsx
  remix/app/components/Header/index.tsx
  remix/app/components/NewsletterList/index.test.tsx
  remix/app/components/NewsletterList/index.tsx
  remix/app/repositories/newsletter.server.test.ts
  remix/app/repositories/newsletter.server.ts
  remix/app/routes/_app._index.tsx
  remix/app/routes/_app.newsletter.create.tsx
  remix/app/routes/_app.newsletter.update.$id.test.tsx
  remix/app/routes/_app.newsletter.update.$id.tsx
Labels: type : feature, remix

#116 [#49] [Frontend] As a user I can delete a newsletter
  nextjs-13/package-lock.json
  nextjs-13/package.json
  nextjs-13/public/images/icons/trash.svg
  nextjs-13/src/app/page.tsx
  nextjs-13/src/components/CreateNewsletterModal/index.test.tsx
  nextjs-13/src/components/CreateNewsletterModal/index.tsx
  nextjs-13/src/components/ListNewsletter/index.tsx
  nextjs-13/src/components/NewsletterItem/index.test.tsx
  nextjs-13/src/components/NewsletterItem/index.tsx
  nextjs-13/src/lib/showAlert.ts
  nextjs-13/src/stylesheets/components/_list-newsletter.scss
  nextjs-13/src/stylesheets/screens/_home.scss
  nextjs-13/yarn.lock
Labels: type : feature

#117 [#46] [Backend] As a user I can edit a newsletter
  nextjs-13/src/app/api/v1/newsletter/[id]/route.test.ts
  nextjs-13/src/app/api/v1/newsletter/[id]/route.ts
  nextjs-13/src/repositories/newsletter.repository.test.ts
  nextjs-13/src/repositories/newsletter.repository.ts
Labels: type : feature

#118 [#47] [Frontend] As a user I can edit a newsletter
  nextjs-13/public/images/icons/edit.svg
  nextjs-13/src/app/page.tsx
  nextjs-13/src/components/CreateNewsletterModal/index.test.tsx
  nextjs-13/src/components/ListNewsletter/index.tsx
  nextjs-13/src/components/NewsletterItem/index.tsx
  nextjs-13/src/components/NewsletterModal/index.test.tsx
  nextjs-13/src/components/NewsletterModal/index.tsx
  nextjs-13/src/repositories/newsletter.repository.test.ts
  nextjs-13/src/repositories/newsletter.repository.ts
  nextjs-13/src/stylesheets/components/_index.scss
  nextjs-13/src/stylesheets/components/_list-newsletter.scss
  nextjs-13/src/stylesheets/components/_newsletter-modal.scss
Labels: type : feature

#121 [#50] [Backend] As a user I can send a newsletter to a recipient
  nextjs-13/.env.sample
  nextjs-13/Makefile
  nextjs-13/README.md
  nextjs-13/jest.config.js
  nextjs-13/package-lock.json
  nextjs-13/package.json
  nextjs-13/src/app/api/v1/newsletter/[id]/route.ts
  nextjs-13/src/app/api/v1/newsletter/route.test.ts
  nextjs-13/src/app/api/v1/newsletter/route.ts
  nextjs-13/src/app/api/v1/newsletter/send/route.test.ts
  nextjs-13/src/app/api/v1/newsletter/send/route.ts
  nextjs-13/src/lib/request/error.ts
  nextjs-13/src/mailers/newsletterInvite.hbs
  nextjs-13/src/repositories/newsletter.repository.test.ts
  nextjs-13/src/repositories/newsletter.repository.ts
  nextjs-13/src/workers/email.worker.ts
  nextjs-13/src/workers/sendMail.test.ts
  nextjs-13/src/workers/sendMail.ts
  nextjs-13/yarn.lock
Labels: type : feature

#123 [#51] [Frontend] As a user I can send a newsletter to a recipient
  nextjs-13/package-lock.json
  nextjs-13/package.json
  nextjs-13/src/app/auth/sign-in/page.test.tsx
  nextjs-13/src/app/auth/sign-in/page.tsx
  nextjs-13/src/app/page.test.tsx
  nextjs-13/src/app/page.tsx
  nextjs-13/src/app/send/page.test.tsx
  nextjs-13/src/app/send/page.tsx
  nextjs-13/src/components/AppLayout/index.test.tsx
  nextjs-13/src/components/AppLayout/index.tsx
  nextjs-13/src/components/AuthLayout/index.test.tsx
  nextjs-13/src/components/AuthLayout/index.tsx
  nextjs-13/src/components/Header/index.test.tsx
  nextjs-13/src/components/Header/index.tsx
  nextjs-13/src/components/MultiSelectWrapper/index.test.tsx
  nextjs-13/src/components/MultiSelectWrapper/index.tsx
  nextjs-13/src/components/NewsletterModal/index.test.tsx
  nextjs-13/src/middleware.ts
  nextjs-13/src/stylesheets/components/_index.scss
  nextjs-13/src/stylesheets/components/_multi-select.scss
  nextjs-13/src/stylesheets/layouts/_default.scss
  nextjs-13/src/stylesheets/screens/_home.scss
  nextjs-13/src/stylesheets/screens/_index.scss
  nextjs-13/src/stylesheets/screens/_send-newsletter.scss
  nextjs-13/yarn.lock
Labels: type : feature

#127 [#53] [Frontend] As a guest I can view a newsletter content
  nextjs-13/src/app/app.tsx
  nextjs-13/src/app/newsletter/[id]/page.test.tsx
  nextjs-13/src/app/newsletter/[id]/page.tsx
  nextjs-13/src/app/send/page.tsx
  nextjs-13/src/components/NewsletterDetail/index.test.tsx
  nextjs-13/src/components/NewsletterDetail/index.tsx
  nextjs-13/src/components/PublicLayout/index.test.tsx
  nextjs-13/src/components/PublicLayout/index.tsx
  nextjs-13/src/middleware.ts
  nextjs-13/src/stylesheets/layouts/_app.scss
  nextjs-13/src/stylesheets/layouts/_index.scss
  nextjs-13/src/stylesheets/layouts/_public.scss
  nextjs-13/src/stylesheets/screens/_index.scss
  nextjs-13/src/stylesheets/screens/_view-newsletter.scss
Labels: type : feature

#33 [#28] Set up frontend application for UI rendering
  nestjs/client/index.html
  nestjs/package-lock.json
  nestjs/package.json
  nestjs/public/assets/stylesheets/application.scss
  nestjs/public/assets/stylesheets/base/_index.scss
  nestjs/public/assets/stylesheets/base/_root.scss
  nestjs/public/assets/stylesheets/base/_typography.scss
  nestjs/public/assets/stylesheets/components/_index.scss
  nestjs/public/assets/stylesheets/layouts/_auth.scss
  nestjs/public/assets/stylesheets/layouts/_default.scss
  nestjs/public/assets/stylesheets/layouts/_index.scss
  nestjs/public/assets/stylesheets/mixins/_chromeless.scss
  nestjs/public/assets/stylesheets/mixins/_index.scss
  nestjs/public/assets/stylesheets/screens/_index.scss
  nestjs/public/assets/stylesheets/screens/_sign-in.scss
  nestjs/src/app.controller.spec.ts
  nestjs/src/app.controller.ts
  nestjs/src/app.module.ts
  nestjs/src/app.service.ts
  nestjs/src/auth/auth.controller.ts
  nestjs/src/auth/strategies/google.strategy.ts
  nestjs/src/main.ts
  nestjs/src/newsletter/newsletter.controller.ts
  nestjs/src/newsletter/newsletter.module.ts
  nestjs/src/newsletter/newsletter.service.ts
  nestjs/src/user/v1/me.controller.ts
  nestjs/views/layouts/default.ejs
  nestjs/views/newsletter/index.ejs
Labels: type : chore

#129 Refactor API endpoints into Server Actions
  nextjs-13/next.config.js
  nextjs-13/src/app/actions/actions.test.tsx
  nextjs-13/src/app/actions/actions.tsx
  nextjs-13/src/app/actions/newsletter.tsx
  nextjs-13/src/app/api/v1/newsletter/[id]/route.test.ts
  nextjs-13/src/app/api/v1/newsletter/[id]/route.ts
  nextjs-13/src/app/api/v1/newsletter/route.test.ts
  nextjs-13/src/app/api/v1/newsletter/route.ts
  nextjs-13/src/app/api/v1/newsletter/send/route.test.ts
  nextjs-13/src/app/api/v1/newsletter/send/route.ts
  nextjs-13/src/app/page.test.tsx
  nextjs-13/src/app/send/page.test.tsx
  nextjs-13/src/app/send/page.tsx
  nextjs-13/src/components/ListNewsletter/index.test.tsx
  nextjs-13/src/components/NewsletterItem/index.test.tsx
  nextjs-13/src/components/NewsletterItem/index.tsx
  nextjs-13/src/components/NewsletterModal/index.test.tsx
  nextjs-13/src/components/NewsletterModal/index.tsx
  nextjs-13/src/config/auth.ts
  nextjs-13/src/lib/request/getServerSession.ts
  nextjs-13/src/lib/withAuth/withAuth.ts
  nextjs-13/src/repositories/newsletter.repository.test.ts
  nextjs-13/src/repositories/newsletter.repository.ts
  nextjs-13/src/workers/sendMail.test.ts
  nextjs-13/src/workers/sendMail.ts
Labels: type : chore
